package biomechazard.content.blocks;

import arc.Core;
import arc.func.Func;
import mindustry.gen.Building;
import mindustry.graphics.Pal;
import mindustry.world.blocks.storage.CoreBlock;
import mindustry.world.meta.Stat;
import mindustry.world.meta.StatUnit;
import mindustry.ui.Bar;

// It's good practice to place custom blocks within a package, e.g., 'yourmod.content'.
// For this conversion, we'll assume it's in a context where Mindustry classes are accessible.

public class CoreCage extends CoreBlock {

    // Constants for power production and efficiency.
    // Using 'final static' for constants that are shared across all instances and never change.
    private final static float POWER_PRODUCTION = 9f;
    private final static Stat GENERATION_TYPE = Stat.basePowerGeneration;
    private final static float PRODUCTION_EFFICIENCY = 1.0f;

    public CoreCage(String name) {
        super(name);

        // Block properties from the original JavaScript code.
        // 'this.' is used for clarity but is optional for direct field access.
        this.hasPower = true;
        this.outputsPower = true;
        this.consumesPower = false;
        this.baseExplosiveness = 10f;
        // Ensure float division for thrusterLength to get a precise result.
        this.thrusterLength = 46f / 4f; 
        
        // Mindustry blocks typically have a category and requirements.
        // Since the original JS code did not specify these, they are omitted here for direct translation.
        // Example:
        // this.category = Category.effect;
        // this.requirements(Category.effect, ItemStack.of(Items.copper, 100));
    }

    /**
     * Overrides the default setStats method to add custom statistics for the block.
     * This is used to display information in the game's block info panel.
     */
    @Override
    public void setStats() {
        super.setStats();
        // The original JS code multiplies powerProduction by 60, likely converting
        // a per-tick value to a per-second or per-minute display for stats.
        this.stats.add(GENERATION_TYPE, POWER_PRODUCTION * 60, StatUnit.powerSecond);
    }

    /**
     * Overrides the default setBars method to add custom bars to the block's UI.
     * This is used to display dynamic information like power output.
     */
    @Override
    public void setBars() {
        super.setBars();
        // Adds a bar named "poweroutput" that displays the block's power generation.
        // The lambda expression `entity -> new Bar(...)` directly translates the JS arrow function.
        this.addBar("poweroutput", entity -> new Bar(
            // The text displayed on the bar, formatted using Mindustry's bundle system.
            // The string "bar.poweroutput" would need to be defined in a localization file (e.g., .properties).
            () -> Core.bundle.format("bar.poweroutput", POWER_PRODUCTION * 60),
            // The color of the bar, using Mindustry's predefined palette for power.
            () -> Pal.powerBar,
            // The fill percentage of the bar (0f to 1f). Since it's a constant output, it's always full.
            () -> 1f
        ));
    }

    /**
     * This method is crucial for Mindustry Java to create and return an instance
     * of your custom build class when the block is placed in the game world.
     * It overrides the default `create` method from the `Block` class.
     */
    /*@Override
    public Building create(int tileX, int tileY) {
        return new CoreCageBuild();
    }*/

    /**
     * This nested class represents the custom build type for the CoreCage block.
     * It contains the runtime logic for the block instance placed in the world.
     * The `getPowerProduction` logic from the original JavaScript's `buildType` is placed here.
     *
     * Note: While `getPowerProduction()` on a `CoreBuild` is not a standard Mindustry Java
     * API for power generation (which usually involves `PowerGenerator` blocks or setting
     * `powerOutput` on the block itself), this directly translates the behavior specified
     * in the original JavaScript code.
     */
    public class CoreCageBuild extends CoreBlock.CoreBuild {
        /**
         * Overrides the getPowerProduction method to define the power generated by this core build.
         * This method is called by the game engine to determine how much power this build contributes.
         */
        @Override
        public float getPowerProduction() {
            // Calculates the power production using the constants defined in the outer CoreCage class.
            // Static members of the outer class can be accessed directly.
            return POWER_PRODUCTION * PRODUCTION_EFFICIENCY;
        }
    }
}

