package biomechazard.world.blocks.storage;

import arc.Core;
import arc.func.Func;
import mindustry.world.blocks.liquid.*;
import mindustry.game.*;
import mindustry.gen.Building;
import mindustry.graphics.Pal;
import mindustry.type.*;
import mindustry.world.*;
import mindustry.world.blocks.storage.CoreBlock;
//import mindustry.world.meta.Stat;
//import mindustry.world.meta.StatUnit;
import mindustry.world.meta.*;
import mindustry.ui.Bar;

/**
* Les noyaux Quarkhod sont différents des noyaux originaux : 
* - Ils peuvent être construit n'importe où, sans nécessiter une zone de noyau. 
* - Ils produisent de l'énergie, agissant comme une centrale. 
* - Ils peuvent stocker les fluides et les redistribuer comme les réservoirs. 
* - Toute capacité additionnelle spécifique sera traitée dans sa propre classe. 
*/
public class CoreQuarkhod extends CoreBlock {
	//3 quantité d'énergie par tick * 60 ticks(1 sec.) = 180 unités d'énergie de base dans le jeu par seconde
	public float powerProduction = 3f;
	
	public CoreQuarkhod(String name) {
		super(name);
		
        update = true;
        solid = true;
        noUpdateDisabled = true;
		unitMoveBreakable = false;
		floating = true;
		placeableLiquid = true;
		requiresCoreZone = false; //Pour que le noyau soit constructible n'importe où, cet attribut ne suffit pas.
		
		hasPower = true;
		consumesPower = false;
		outputsPower = true;
		conductivePower = true;
		
		/** 
		* À faire : ajouter la capacité au noyau de stocker des liquides. Pour l'instant
		* le noyau affiche les infos mais n'accepte pas les liquides.
		*/
		hasLiquids = true;
		liquidCapacity = 700; //Même capacité de base que le petit réservoir basique.
		liquidPressure = liquidCapacity / 10;
		isDuct = true;
		outputsLiquid = true;
	}
	
	/**
     * Cette méthode indique si le noyau est constructible sur l'emplacement indiqué. 
     * Pour l'instant, on utilise le même comportement que si on était dans l'éditeur. 
     * Peut causer des erreurs. 
     */
	@Override
	public boolean canPlaceOn(Tile tile, Team team, int rotation){
		if(tile == null) return false;
		return true;
	}
	
	/**
     * La méthode setStats de CoreBlock ne contient pas d'information énergétique puisque
	 * les noyaux basiques ne sont pas des générateurs d'énergie. Il faut donc ajouter 
     * manuellement les stats pour l'afficheur du bloc.
     */
    @Override
    public void setStats() {
        super.setStats();
        stats.add(Stat.basePowerGeneration, powerProduction, StatUnit.powerSecond);
    }

    /**
     * La méthode setBars de CoreBlock ne contient pas de jauge énergétique puisque
	 * les noyaux basiques ne sont pas des générateurs d'énergie. Il faut donc ajouter 
     * manuellement la jauge sur l'afficheur du bloc.
     */
    @Override
    public void setBars() {
        super.setBars();
        addBar("poweroutput", entity -> new Bar(
            // The string "bar.poweroutput" is defined in the localization file "bundle".
            () -> Core.bundle.format("bar.poweroutput", powerProduction * 60),
            // The color of the bar, using Mindustry's predefined palette for power.
            () -> Pal.powerBar,
            // The fill percentage of the bar (0f to 1f). Since it's a constant output, it's always full.
            () -> 1f
        ));
    }
	
	/**
     * This nested class represents the custom build type for the CoreCage block.
     * It contains the runtime logic for the block instance placed in the world.
     *
     * Note: While `getPowerProduction()` on a `CoreBuild` is not a standard Mindustry Java
     * API for power generation (which usually involves `PowerGenerator` blocks or setting
     * `powerOutput` on the block itself), this override is mandatory, since a CoreBlock is 
     * not a PowerBlock, to force this specific behavior.
     */
    public class CoreQuarkhodBuild extends CoreBlock.CoreBuild {
        /**
         * Overrides the getPowerProduction method to define the power generated by this core build.
         * This method is called by the game engine to determine how much power this build contributes.
         */
        @Override
        public float getPowerProduction() {
            return powerProduction;
        }
		
		@Override
        public void updateTile(){
            iframes -= Time.delta;
            thrusterTime -= Time.delta/90f;
			dumpLiquid(liquids.current());
        }
		
		@Override
        public boolean acceptLiquid(Building source, Liquid liquid){
            return (liquids.current() == liquid || liquids.currentAmount() < 0.2f);
        }
    }

}


